.PHONY: clean destroy
.SHELL = /bin/bash
BINDIR = ../../bin/
SRCDIR = ../../src/
OPTIONWPLT = ../scripts/optionW.plt
FASTQ = test_1.fastq.gz test_2.fastq.gz
DB = hiv.fasta

FIRST = 0
LAST = 30
INCREMENT = 1

NUMBERS = $(shell seq ${FIRST} ${INCREMENT} ${LAST})

# Make sure you have the last version of gnuplot

optionW.png: optionW.txt
	gnuplot -c ${OPTIONWPLT} $(basename, $@).svg \'$<\' '(($$0+'${FIRST}')*'${INCREMENT}')'
	inkscape -z -y 1.0 -e $@ $(basename, $@).svg

optionW.txt: $(addprefix ${BINDIR}, blast2bam fastq2fasta) db.dict ${FASTQ} $(addsuffix .nin, ${DB})
	$(foreach var, ${NUMBERS}, \
		$(addprefix ${BINDIR}, fastq2fasta) ${FASTQ} | \
		blastn -db ${DB} -num_threads 4 -word_size 8 -outfmt 5 | \
		$(addprefix ${BINDIR}, blast2bam) -W $(var) -R '@RG	ID:foo	SM:sample' - db.dict ${FASTQ} | \
		samtools view -Sub -F 0xF00 - | samtools sort - results > results.bam ; \
		samtools index results.bam ; \
		samtools idxstats results.bam | paste - - >> $@ ;)

$(addprefix ${BINDIR}, blast2bam fastq2fasta):
	(cd ${SRCDIR}; ${MAKE})

db.dict: ${DB}
	picard-tools CreateSequenceDictionary R=$< O=$@

$(addsuffix .nin, ${DB}): ${DB}
	makeblastdb -in $< -dbtype 'nucl'

# Clean
clean:
	rm -f results.bam results.bam.bai db.dict *.nhr *.nin *.nsq optionW*
	
destroy: clean
	(cd ${SRCDIR}; ${MAKE} clean)
