.PHONY: clean destroy bamfiles all
.SHELL = /bin/bash
BINDIR = ../../bin
SRCDIR = ../../src
SCRIPTDIR = ../scripts
FF = fastq2fasta
FASTQ = test_1.fastq.gz test_2.fastq.gz
DB = hiv.fasta

FIRST = 8
LAST = 28
INCREMENT = 2

NUMBERS = $(shell seq ${FIRST} ${INCREMENT} ${LAST})

# Make sure you have the last version of gnuplot

all: bamfiles nbReads.png coverage.png

nbReads.png:
	gnuplot -c ${SCRIPTDIR}/nbReads.plt $(basename $@).svg \'nbReads.txt\' '(($$0*'${INCREMENT}')+'${FIRST}')' 822480
	inkscape -z -y 1.0 -e $@ $(basename $@).svg

coverage.png:
	gnuplot -c ${SCRIPTDIR}/coverage.plt $(basename $@).svg \'coverage.txt\' '(($$0*'${INCREMENT}')+'${FIRST}')' 9181
	inkscape -z -y 1.0 -e $@ $(basename $@).svg

bamfiles: ${BINDIR}/blast2bam ${FASTQ} ${DB}.nin
	$(foreach var, ${NUMBERS}, \
		${FF} ${FASTQ} | \
		blastn -db ${DB} -num_threads 4 -word_size $(var) -outfmt 5 | \
		${BINDIR}/blast2bam -R '@RG\tID:foo\tSM:sample' - ${DB} ${FASTQ} | \
		samtools view -Sub -F 0xF00 - | samtools sort - > results.$(var).bam ; \
		samtools index results.$(var).bam ; \
		samtools idxstats results.$(var).bam | paste - - >> nbReads.txt ; \
		samtools depth results.$(var).bam > depth.$(var).txt ; \
		wc -l depth.$(var).txt >> coverage.txt ; \
		gnuplot -c ${SCRIPTDIR}/depth.plt depth.$(var).svg \'depth.$(var).txt\' ; \
		inkscape -z -y 1.0 -e depth.$(var).png depth.$(var).svg ;)

${BINDIR}/blast2bam:
	(cd ${SRCDIR}; ${MAKE})

${DB}.nin: ${DB}
	makeblastdb -in $< -dbtype 'nucl'

# Clean
clean:
	rm -f *.bam *.bam.bai *.nhr *.nin *.nsq *.txt *.svg *.png
	
destroy: clean
	(cd ${SRCDIR}; ${MAKE} clean)
