.PHONY: all idxstats flagstats optionW
.SHELL = /bin/bash
TESTDIR = ../

all: idxstats flagstats optionW

idxstats: $(addprefix ${TESTDIR}, results.bam resultsBWA.bam)
	$(foreach bam, $(addprefix ${TESTDIR}, *.bam), \
		samtools idxstats $(bam) | paste - - > $(addsuffix .idxstats.txt, $(basename, $(bam)));)

flagstats: $(addprefix ${TESTDIR}, results.bam resultsBWA.bam)
	$(foreach bam, $(addprefix ${TESTDIR}, *.bam), \
		samtools flagstat $(bam) > $(addsuffix .flagstat.txt, $(basename, $(bam)));)

optionW:
	${MAKE} -f Makefile.optionW LAST=100 INCREMENT=5

